### ISSUE TITLE
Binary Data Generation

### ISSUE THREAD

**Issue by igor17400** [ShawnChenn/FairNeg#4]
Congratulations on the publication!

In the paper, you mention the necessity of using binary item attributes in the datasets. With that in mind, would it be possible to release the datasets for `ML1M-4`, `ML1M-2`, `Amazon-4`, and `Amazon-2`? 

Alternatively, could you indicate where in the code the dataset generation process is located?

Thank you :)

**Comment by ShawnChenn** [comment]
Thanks for your attention, we just follow the data generation pipeline, as detailed in the jupyter notebooks in https://github.com/Zziwei/Item-Underrecommendation-Bias.
